### ISSUE TITLE
[BUG] syncing-server-js latest fails to start

### ISSUE THREAD

**Issue by Spider-One** [standardnotes/self-hosted#104]
**Service Versions:**
```
Container                             Repository                        Tag                 Image Id            Size
api-gateway-standalone                standardnotes/api-gateway         latest              50e9e84acd1e        204MB
auth-standalone                       standardnotes/auth                latest              0373139abbc1        218MB
auth-worker-standalone                standardnotes/auth                latest              0373139abbc1        218MB
cache-standalone                      redis                             6.0-alpine          f30aed8202b4        26.3MB
db-standalone                         mysql                             5.6                 dd3b2a5dcb48        303MB
files-standalone                      standardnotes/files               latest              40fb3ed5c575        206MB
syncing-server-js-standalone          standardnotes/syncing-server-js   latest              353e497fbbfb        219MB
syncing-server-js-worker-standalone   standardnotes/syncing-server-js   latest              353e497fbbfb        219MB
```

**Describe the bug**
syncing-server-js-standalone fails to start on the start-web command and produces the error below. This was after performing ./server.sh update which only applied image updates (compose and env files were current)

**To Reproduce**
Failed on my existing docker stack which was previously working. Also tried after ./server.sh cleanup and with a fresh server creation which fail with the same error

**Expected behaviour**
Should start up cleanly

**Logs**
```
[Docker] Starting Web...
Internal Error: Error when performing the request
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/corepack/dist/corepack.js:16064:20)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Additional context**
Tried previous version tags of syncing-server-js but could not get it to start up cleanly (tried 3 previous to latest). Might be an issue related to another image update? api-gateway and auth images also updated but seem to simply be waiting for syncing-server-js to start up.

**Comment by Spider-One** [comment]
Looks like syncing-server-js may simply be relaying the error from the files-standalone container, which is odd since that was running fine before the update and it's image did not update

**Comment by Spider-One** [comment]
Well I'm dumb, it was a DNS issue

**Comment by Spider-One** [comment]
Well I'm done it was a DNS issue

**Comment by dm5n** [comment]
What was the DNS issue?

**Comment by Spider-One** [comment]
I made a mistake updating my pi-hole host and lost access to pi-hole so my PC running Standard Notes lost internet access
