### ISSUE TITLE
Standard notes won't start after reboot

### ISSUE THREAD

**Issue by robertrud** [standardnotes/self-hosted#95]
**Service Versions
```
             Container                          Repository                 Tag         Image Id       Size
------------------------------------------------------------------------------------------------------------
api-gateway-standalone                standardnotes/api-gateway         latest              8ee490b06d17        204MB
auth-standalone                       standardnotes/auth                latest              674f7ed1b962        218MB
auth-worker-standalone                standardnotes/auth                latest              674f7ed1b962        218MB
cache-standalone                      redis                             6.0-alpine          b5a61c880115        24.6MB
db-standalone                         mysql                             5.6                 dd3b2a5dcb48        303MB
files-standalone                      standardnotes/files               latest              99dd5d25922d        206MB
syncing-server-js-standalone          standardnotes/syncing-server-js   latest              49aea6845bbc        217MB
syncing-server-js-worker-standalone   standardnotes/syncing-server-js   latest              49aea6845bbc        217MB
workspace-standalone                  standardnotes/workspace           latest              e96e83bb8eff        216MB
workspace-worker-standalone           standardnotes/workspace           latest              e96e83bb8eff        216MB

```

I'm running Standard notes self-hosted and web client on Ubuntu 22.04 vps server (16GB RAM) Everything works fine untill I reboot the server. After that services won't come up. I have to manually start/restart both the server and web app. Am I missing something? Please see the errors in 'status' and 'logs'.
Usually it takes about a minute for the services to come up. Even if I wait 10 mins or more after reboot nothing happens.

**status**
Services State:
NAME                                  COMMAND                  SERVICE                    STATUS              PORTS
api-gateway-standalone                "./packages/api-gate…"   api-gateway                running             0.0.0.0:3000->3000/tcp, :::3000->3000/tcp
auth-standalone                       "./packages/auth/wai…"   auth                       running             
auth-worker-standalone                "./packages/auth/wai…"   auth-worker                running             
**cache-standalone                      "docker-entrypoint.s…"   cache                      exited (0)          
db-standalone                         "docker-entrypoint.s…"   db                         exited (0)**          
files-standalone                      "./packages/files/wa…"   files                      running             0.0.0.0:3125->3000/tcp, :::3125->3000/tcp
syncing-server-js-standalone          "./packages/syncing-…"   syncing-server-js          running             
syncing-server-js-worker-standalone   "./packages/syncing-…"   syncing-server-js-worker   running             
workspace-standalone                  "./packages/workspac…"   workspace                  running             
workspace-worker-standalone           "./packages/workspac…"   workspace-worker           running 

**Logs**
files-standalone                     | nc: bad address 'db'
files-standalone                     | waiting for db:3306...
workspace-standalone                 | nc: bad address 'db'
workspace-standalone                 | db:3306 is unavailable yet - waiting for it to start
workspace-worker-standalone          | nc: bad address 'db'
workspace-worker-standalone          | db:3306 is unavailable yet - waiting for it to start
syncing-server-js-standalone         | nc: bad address 'db'
syncing-server-js-standalone         | db:3306 is unavailable yet - waiting for it to start
api-gateway-standalone               | auth:3000 is unavailable yet - waiting for it to start
auth-worker-standalone               | nc: bad address 'db'
auth-worker-standalone               | db:3306 is unavailable yet - waiting for it to start
syncing-server-js-worker-standalone  | nc: bad address 'db'
syncing-server-js-worker-standalone  | db:3306 is unavailable yet - waiting for it to start
auth-standalone                      | nc: bad address 'db'
auth-standalone                      | db:3306 is unavailable yet - waiting for it to start

**Comment by jackyzy823** [comment]
you `db` and `redis` are exited. have you tried to maually start it ( like `docker-compose up -d db`  and `docker-compose up -d cache` ) and see if they still exit after starting.

**Comment by robertrud** [comment]
Yes, after a reboot I have to start services manually. Then it works again untill next reboot. I just don't know why. I'll investigate further. Is anyone else experiencing similar problems?

**Comment by fr0st-beard** [comment]
Hi, I just want to add that this also happens to me. I'm using the server.sh in the repo to start/stop/update my server and everything is up-to-date. It worked perfectly until I updated a few weeks ago. I'm happy to provide any info anyone might need. Just let me know.

**Comment by fr0st-beard** [comment]
Hi @karolsojko! Thanks for following up. I ran ./server.sh update and it ended with the following message:

> Checking for env file changes
> The .env file contains different amount of lines than .env.sample. This may be caused by the fact that there is a new environment variable to configure. Please update your environment file and try again.

Not out of the ordinary for an update, but when I run it again with zero changes I get this:

> ./server.sh: 50: ./server.sh: function: not found
> ./server.sh: 51: local: not in a function

In fact, any time I run server.sh after it pulls the changes from git I get that same error. 

I checked, and line 50 of server.sh starts with:

`function cleanup {
  local output_logs=$1
  if [ $output_logs == 1 ]
  then
    echo "Outputing last 100 lines of logs"
    $DOCKER_COMPOSE_COMMAND logs --tail=100
  fi
}`

Can't start it at all now, unfortunately.

**Comment by karolsojko** [comment]
Thanks @fr0st-beard - should be fixed now

**Comment by macdonaldj** [comment]
im getting something similar on the latest. the DB and redis after reboot show exited as status.

looks like DB didnt try to restart on boot


```
2023-01-13T15:05:28.559693442Z 2023-01-13 15:05:28 1 [Note] mysqld: Shutdown complete
2023-01-13T15:05:28.559889594Z

root@ip-172-31-29-166:/opt/jerboa/standardnotes/self-hosted# uptime
 15:09:27 up 3 min,  1 user,  load average: 0.18, 0.47, 0.24
root@ip-172-31-29-166:/opt/jerboa/standardnotes/self-hosted# date
Fri Jan 13 15:09:29 UTC 2023
```

doesnt look like it tried to start back up after being shutdown

same for redis

```
2023-01-13T15:05:24.956732486Z 1:M 13 Jan 2023 15:05:24.942 # User requested shutdown...
2023-01-13T15:05:24.956758826Z 1:M 13 Jan 2023 15:05:24.942 * Saving the final RDB snapshot before exiting.
2023-01-13T15:05:24.984931146Z 1:M 13 Jan 2023 15:05:24.947 * DB saved on disk
2023-01-13T15:05:24.984960296Z 1:M 13 Jan 2023 15:05:24.947 # Redis is now ready to exit, bye bye...
```

**Comment by macdonaldj** [comment]
my fix was  updating the docker-compose and changed restart to unless-stopped as well as added it to localstack
