### ISSUE TITLE
GET error attempting to access /extensions/index.json

### ISSUE THREAD

**Issue by dm5n** [standardnotes/self-hosted#99]
**Service Versions (please complete the following information):**
Paste the output of `./server.sh version`. For example:
```
Container                             Repository                        Tag                 Image Id            Size
api-gateway-standalone                standardnotes/api-gateway         latest              060cf5bcf09c        202MB
auth-standalone                       standardnotes/auth                latest              ceb3d0f90d3c        216MB
auth-worker-standalone                standardnotes/auth                latest              ceb3d0f90d3c        216MB
cache-standalone                      redis                             6.0-alpine          ddf87e4ac647        24.4MB
db-standalone                         mysql                             8                   e8ff7e619492        550MB
files-standalone                      standardnotes/files               latest              ad69fa3dd79c        204MB
syncing-server-js-standalone          standardnotes/syncing-server-js   latest              cffee2da828e        214MB
syncing-server-js-worker-standalone   standardnotes/syncing-server-js   latest              cffee2da828e        214MB
```

**Describe the issue**
I followed [this guide](https://theselfhostingblog.com/posts/how-to-completely-self-host-standard-notes/) to install extensions repository. But getting a GET error trying to access notes.example.com/extensions/index.json

I'm wondering if it's a permissions issue?

**Comment by jackyzy823** [comment]
This guide is outdated. the official extensions (which called features now) are already included in the frontend , you only need a subscription (via ./server.sh create-subscription for self host user) to use it.

Ref: https://github.com/standardnotes/forum/issues/1840


For 3rd extensions. you may  install plugin one by one via "Preferences" -> "General" -> "Advanced Options" -> "Install External Package". docs: https://github.com/standardnotes/plugins

**Comment by dm5n** [comment]
Thankyou – that's helpful. 

Should I also remove the modifications made by following the outdated guide – including the standardnotes–extensions folder and the changes to nginx.conf files?

**Comment by jackyzy823** [comment]
You can remove it if you want.
